In [4]:
import numpy as np

a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a, 0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [15]:
np_ones = np.ones((1,2,1,3))
print(np_ones)
print(np_ones.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
(1, 2, 1, 3)


In [14]:
sq = np.squeeze(np_ones)
print(sq)
print(sq.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [10]:
a = [1,2,2,3,3,4,3,2,4,1]

u_a, counts = np.unique(a, return_counts = True)
print(u_a)
print(counts)

[1 2 3 4]
[2 3 3 2]


In [11]:
a = [1,2,2,3,3,4,3,2,4,1]

u_a, indexs = np.unique(a, return_index = True)
print(u_a)
print(indexs)

[1 2 3 4]
[0 1 3 5]


In [12]:
a = [1,2,2,3,3,4,3,2,4,1]
# unique(index를 먼저 쓰던 count를 먼저 쓰던 출력은 index부터)
u_a, indexs, counts = np.unique(a, return_index = True, return_counts = True)
print(u_a)
print(indexs)
print(counts)

[1 2 3 4]
[0 1 3 5]
[2 3 3 2]


In [16]:
a = np.array([1,4,2,3])
b = np.sort(a) # a[np.argsort(a)]
print(f'a {a}')
print(f'b {b}')
c = np.argsort(a)
print(f'c {c}')
print(f'cc {a[c]}')
a.sort()
print(f'a {a}')

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]


In [19]:
a = np.array([1,4,2,3])
np.mean(a)

2.5

In [23]:
np.std(a)

1.118033988749895

In [24]:
np.var(a)

1.25

In [25]:
np.max(a)

4

In [27]:
np.min(a)

1

In [28]:
np.median(a)

2.5

In [79]:
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
# 1번
uq = np.unique(a)
print(uq)

[  1   2   3   4   5   7   8   9  10  11  24 100]


In [37]:
# 2번
print(np.max(uq))
print(np.min(uq))
print(np.mean(uq))

100
1
15.333333333333334


In [39]:
# 3번, 4번
print(np.sum(uq))
print(np.median(a))

184
5.0


In [81]:
x = np.arange(15, dtype= np.int64).reshape(3,5)
x[1:, ::2] = -99

print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [52]:
print(np.max(x[:,0]))
# np.max(x,axis=0)[0]
print(np.min(x[:,0]))
print(np.mean(x[:,0]))

0
-99
-66.0


In [87]:
print(np.sum(x[1]))
# print(np.sum(x, axis=1)[1])

-283
-283


In [80]:
a = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
b = np.argsort(a)[::-1]
print(a[b])

[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
