In [2]:
print('hello')

hello


In [3]:
print('shift + enter = 다음줄로 넘기기')

shift + enter = 다음줄로 넘기기


In [4]:
print('esc => d 두번, 삭제하기입니다!')

esc => d 두번, 삭제하기입니다!


In [5]:
print('Hello world')

Hello world


In [6]:
a = 1
a

1

In [7]:
b = [1,2,3,4,5]

In [8]:
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
import random
import time
import os

if os.path.exists('word.txt') : # 파일 존재 여부 확인

    with open('word.txt', 'r') as f:
        word = f.read().split() #전역 변수
else :
    word = ['sky', 'earth', 'moon', 'flower', 'tree', 
            'apple', 'grape', 'garlic', 'onion', 'potato']

n = 1

input('[타자게임] 준비되면 엔터!')
start = time.time()

while n <11 :
    print('문제',n)
    question = random.choice(word)
    print(question) # 문제 출제
    user = input()
    if question == user :
        print('통과!!')
        n += 1 # 다음 문제 카운트
    else:
        print('오타! 다시 도전!')

end = time.time()
et = end - start
print(f'타자 시간: {et: .2f}초')

문제 1
garlic
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
earth
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
earth
오타! 다시 도전!
문제 1
flower
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
onion
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
onion
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
onion
오타! 다시 도전!
문제 1
onion
오타! 다시 도전!
문제 1
apple
오타! 다시 도전!
문제 1
sky
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
earth
오타! 다시 도전!
문제 1
apple
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
potato
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
flower
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
moon
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
potato
오타! 다시 도전!
문제 1
flower
오타! 다시 도전!
문제 1
moon
오타! 다시 도전!
문제 1
grape
오타! 다시 도전!
문제 1
apple
오타! 다시 도전!
문제 1
potato
오타! 다시 도전!
문제 1
flower
오타! 다시 도전!
문제 1
sky
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
flower
오타! 다시 도전!
문제 1
tree
오타! 다시 도전!
문제 1
moon
오타! 다시 도전!
문제 1
moon
오타! 다시 도전!
문제 1
garlic
오타! 다시 도전!
문제 1
sky
오타! 다시 도전!
문제 1
potato


KeyboardInterrupt: Interrupted by user

In [6]:
import numpy as np 
x = np.array([3,1,2,'1'])
print(x)
print(([3,1,2,'1']))
print(type(x))
print(type([3,1,2]))

['3' '1' '2' '1']
[3, 1, 2, '1']
<class 'numpy.ndarray'>
<class 'list'>


In [11]:
c = [[1],[1,2]]
# d = np.array([[1],[1,2]]) 오류
d = np.array([[1,1],[1,2]])

for x,y in d:
    print(x,y)

1 1
1 2


In [12]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 9AEB-3250

 c:\Users\kimhi\python-test ���͸�

2024-12-13  ���� 11:39    <DIR>          .
2024-12-13  ���� 11:25    <DIR>          ..
2024-12-13  ���� 11:31    <DIR>          .ipynb_checkpoints
2024-11-30  ���� 10:07             1,044 1.py
2024-12-05  ���� 12:46             1,502 10.py
2024-12-05  ���� 10:01               766 11.py
2024-12-05  ���� 12:46             1,007 12.py
2024-12-05  ���� 01:52             1,628 13.py
2024-12-07  ���� 01:52             2,985 14.py
2024-12-09  ���� 11:21             2,040 15.py
2024-12-10  ���� 10:20             1,813 16.py
2024-12-10  ���� 10:32             2,391 17.py
2024-12-10  ���� 11:37             1,211 18.py
2024-12-10  ���� 01:51             1,902 19.py
2024-11-30  ���� 10:38               576 2.py
2024-12-11  ���� 10:15             2,032 20.py
2024-12-11  ���� 12:33               711 21.py
2024-12-11  ���� 01:22               256 22.py
2024-12-12  ���� 10:15               891 23.py
2024-1

In [17]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [15]:
x = np.array(['1.0', '2.0', '3.0'])
y = np.array(['2.0', '4.0', '6.0'])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> None

In [20]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [21]:
print(x.ndim)

1


In [23]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [25]:
print(a.shape)

(3, 2)


In [27]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)

3


In [29]:
print(a.shape)

(3, 2, 1)


In [30]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)

3


In [31]:
print(a.shape)

(3, 2, 2)


In [32]:
np.dot(4,2)

8

In [33]:
ndar1 = np.array([1,2])
ndar2 = np.array([4,5])
np.dot(ndar1,ndar2)

14

In [35]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [37]:
ndar1 = np.array([[1],[3]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [40]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)
print(a)

(2, 2, 1)
1
[[[1]
  [2]]

 [[3]
  [4]]]
[1 2 3 4]


In [41]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [43]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [44]:
ndarr.reshape(1,6)

array([[1, 2, 2, 3, 3, 4]])

In [45]:
ndarr.flatten() # 1차원?

array([1, 2, 2, 3, 3, 4])

In [46]:
np.random.randint(5,size=(2,4))

array([[2, 4, 4, 1],
       [2, 1, 0, 4]])

In [47]:
np.random.rand(2,4)

array([[0.12232281, 0.60045527, 0.42649047, 0.89874203],
       [0.47806609, 0.09008355, 0.98828644, 0.33072311]])

In [48]:
rng = np.random.default_rng() # 권장장

In [49]:
rng.random()

0.3533705570021066

In [50]:
rng.integers(0,10,(2,4))

array([[5, 0, 0, 1],
       [1, 1, 5, 1]], dtype=int64)

In [51]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [54]:
ndarr[ndarr > 1] # 1차원

array([6, 3, 5, 2, 4])

In [58]:
ndarr[1:]

array([[5, 2],
       [4, 1]])

In [57]:
ndarr[[[ True, True],
       [ True, True],
       [True, False]]]

array([6, 3, 5, 2, 4])

In [45]:
import numpy as np

ex = np.zeros(10)
# ex = [0 for i in range(10)]
print(ex)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
ex[4] = 1
print(ex)

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]


In [23]:
ex1 = np.arange(10,31)
print(ex1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [49]:
rng = np.random.default_rng()
print(rng.integers(0,100,(2,2)))

[[69 71]
 [83 18]]


In [83]:
k = np.random.rand(2,4)
print(k)

[[0.75486652 0.67278048 0.15538951 0.74882702]
 [0.081488   0.18798848 0.59807987 0.14975601]]


In [88]:
k2 = rng.random((2,4))
print(k2)

[[0.74585624 0.47585106 0.60959457 0.00618413]
 [0.04391967 0.40486302 0.44695103 0.34978452]]


In [151]:
arr1 = np.arange(35,75)
# arr1.shape = (10,4) or
arr2 = arr1.reshape(10,4)
print(arr2)


[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [120]:
print(arr2[::-1]) # 역순으로 끝까지 출력.

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [175]:
print(arr2[1:9,2::])
# print(arr2[1:-1, 2:])

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [159]:
print(arr2[:,3]) # 정수 인덱스 => 1차원
# arr2[:, -1]
print(arr2[:,3:4]) # 범위 인덱스 = > 2차원
# arr2[:, -1:]

[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]


In [160]:
arr3 = arr2[:,3:4]
# arr2[::-1,-1:]
print(arr3[::-1])

[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]


In [170]:
arr4 = rng.integers(1,51,(5,6))
# arr4 = rng.integers(1,51, size = (5,6))
arr5 = [j  for i in arr4  for j in i  if j%2 == 0 ]
# arr4[arr4%2 == 0]
print(arr4)
print('짝수만 출력 : ',arr5)

[[19  1 44 13  8 29]
 [45  3  3 17 25  5]
 [48 21 16  2  9 18]
 [13 46 20 34 35 11]
 [41 14  7 21  1  1]]
짝수만 출력 :  [44, 8, 48, 16, 2, 18, 46, 20, 34, 14]
